### ISSUE TITLE
eta^2 result

### ISSUE THREAD

**Issue by philchalmers** [friendly/heplots#1]
Hi Michael and John,

I was wondering if there was a good explanation for the following discrepancy, or if it's just a coding error. I've been checking various packages for computing statistics such as $\eta^2$ and partial $\eta^2$, mostly so that I can demonstrate these concept using regression ideas (e.g., via semi-partial and partial correlations based on correlating residuals, as well as noting how much $R^2$ drops when removing a variable).  

Anyway, during my search I found different packages are providing different results, which to me is surprising, and one of them is in the function `heplots::etesq()` (another that is *very* different is `sjstats::anova_stats()`....not presented below). Below is a replication of what I'm seeing:

```r
data(mtcars)
mtcars <- within(mtcars, {
	cyl <- factor(cyl)
	am <- factor(am, levels=c(0,1), labels=c('automatic', 'manual'))
})

mod <- lm(mpg ~ cyl + am, mtcars)
DescTools::EtaSq(mod) # results I believe are correct

>         eta.sq eta.sq.part
> cyl 0.40531243   0.6331018
> am  0.03265131   0.1220428

# this gives the same
# lsr::etaSquared(mod)

# results from heplots
heplots::etasq(mod) # correct

>           Partial eta^2
> cyl           0.6331018
> am            0.1220428
> Residuals            NA

heplots::etasq(mod, partial=FALSE) # likely NOT correct

>                eta^2
> cyl       0.60237943
> am        0.04852671
> Residuals         NA
```

I suspect `DescTools` is reporting the correct results since $\eta^2$ is really just the semi-partial correlation squared, which can be obtained via R^2 differences after removing the IV of interest. E.g.,

```r
mod_sans_am <- lm(mpg ~ cyl, mtcars)
mod_sans_cyl <- lm(mpg ~ am, mtcars)

# eta^2 for am
summary(mod)$r.squared - summary(mod_sans_am)$r.squared

> 0.03265131

# eta^2 for cyl
summary(mod)$r.squared - summary(mod_sans_cyl)$r.squared

> 0.4053124
```

**Comment by philchalmers** [comment]
Culprit seems to be here: 

https://github.com/friendly/heplots/blob/139f53f600c95b3c4066879ffb1e51458eea8876/R/etasq.R#L67

SST should be defined based on the fixed SS term rather than the sum of the SS terms from `car::Anova()`. This would do it (one of many): 

```r
y <- model.frame(x)[ ,1]
SST <- sum( (y - mean(y))^2 )
```

**Comment by john-d-fox** [comment]
Dear Phil,

Thanks for this and for your previous message. This is Michael's code. If he hasn't already gotten back to you, I expect that he will eventually.

Best,
 John

**Comment by friendly** [comment]
I'll have to revisit this a bit.  `etasq.lm` was written quite a while ago, but was more of an after thought to provide a method analogous to `etasq.mlm` under the generic `etasq`
